### ISSUE TITLE
サーバーの初期化依頼

### ISSUE THREAD

**Issue by i01coach** [coderdojo-japan/dojopaas#104]
CoderDojo【品川御殿山】の【柳沢富夫】です。当該サーバー（IPアドレス：153.120.168.82）の初期化をお願いします。

**Comment by yasulab** [comment]
現在さくらのメンタナンス中のようなので、もしかしたら後日アクセスすると繋がるかもしれません ;)

さくらのクラウド 一部のお客様 [東京第1ゾーン]
https://help.sakura.ad.jp/maint/24906/
https://help.sakura.ad.jp/maint/24939/

**Comment by yasulab** [comment]
コンソールパネルからも操作不能（初期化含む）だったので、僕の方でも後で試してみますね ;)

**Comment by i01coach** [comment]
安川様

それではコントロールパネルが復帰したら教えてもらえますか？

**************************************************
有限会社ラウンドテーブルコム
CEO　柳沢富夫　
tomio.yanagisawa@roundtable.co.jp
tomio.yanagisawa@roundtable.jp
http://www.roundtable.co.jp/
〒141-0031　東京都品川区西五反田8-2-10-707
TEL.03-5434-7524　FAX.03-5434-7694
Mobile: 090-3046-5556

ICT, Education & Active Web Solution
インターネット技術をきっかけに
新たに誕生してくる教育事業をサポートします。

BBCoachプロジェクト事務局長
http://bbcoach.roundtable.jp/　

国際的学習プログラム研究委員会　委員長
http://www.roundtable.co.jp/company/?page_id=366

Twitter:i01coach
FaceBook:tomio.yanagisawa
**************************************************

**Comment by yasulab** [comment]
> それではコントロールパネルが復帰したら教えてもらえますか？

こちらにメンタナンス時間が書かれています!

> さくらのクラウド 一部のお客様 [東京第1ゾーン]
> https://help.sakura.ad.jp/maint/24906/
> https://help.sakura.ad.jp/maint/24939/

**Comment by i01coach** [comment]
安川様

13時から17時ということですね。
了解です。

**Comment by i01coach** [comment]
安川様

18:00に挑戦しましたが、同じ状況でした。
ssh: connect to host 153.120.168.82 port 22: Operation timed out

初期化ですかね。
しかし、どこでおかしくなったのでしょう。

**Comment by yasulab** [comment]
初期化しました! サーバーに接続できますか? 🤔
https://github.com/coderdojo-japan/dojopaas/commit/927826ed7efe2522d6d131836c159271c4935f4b#diff-3dfe38357946121c2f0b04a2f80cec54R35

**Comment by i01coach** [comment]
安川様

無事アクセス出来ました！
ありがとうございました。


**************************************************
有限会社ラウンドテーブルコム
CEO　柳沢富夫　
tomio.yanagisawa@roundtable.co.jp
tomio.yanagisawa@roundtable.jp
http://www.roundtable.co.jp/
〒141-0031　東京都品川区西五反田8-2-10-707
TEL.03-5434-7524　FAX.03-5434-7694
Mobile: 090-3046-5556

ICT, Education & Active Web Solution
インターネット技術をきっかけに
新たに誕生してくる教育事業をサポートします。

BBCoachプロジェクト事務局長
http://bbcoach.roundtable.jp/　

国際的学習プログラム研究委員会　委員長
http://www.roundtable.co.jp/company/?page_id=366

Twitter:i01coach
FaceBook:tomio.yanagisawa
**************************************************

**Comment by yasulab** [comment]
よかったです😆 無事アクセスできたとのことなので、こちらの Issue 閉じちゃいますね ;)
