### ISSUE TITLE
サーバーの初期化依頼

### ISSUE THREAD

**Issue by coderdojo-nago** [coderdojo-japan/dojopaas#107]
CoderDojo名護の安藤元気です。当該サーバー（IPアドレス：153.127.219.132）の初期化をお願いします。

MacのターミナルでSSHの接続を試みたところ、反応がないか以下のメッセージが表示され、接続することができませんでした。
ssh_exchange_identification: Connection closed by remote host
ssh_exchange_identification: read: Connection reset by peer

初期化することで接続することができるようにならないかと思い、依頼します。

**Comment by yasulab** [comment]
以前にも似たような状況があったので、一旦リブートしてみました！
cf. https://github.com/coderdojo-japan/dojopaas/pull/105

もう一度接続を試してみてもらえませんか? (＞人＜ )✨

**Comment by yasulab** [comment]
よかったです! こちらの Issue は閉じておきますね ;)
