### ISSUE TITLE
サーバーの初期化依頼

### ISSUE THREAD

**Issue by gah00501** [coderdojo-japan/dojopaas#114]
CoderDojoとよなか（豊中）の物井孝雄 です。当該サーバー（IPアドレス：【153.125.128.121】）の初期化をお願いします。

**Comment by yasulab** [comment]
ひとまず再起動で対応してみました! もう一度 SSH 試してもらえると助かります (＞人＜ )✨
cf. https://github.com/coderdojo-japan/dojopaas/pull/113#issuecomment-453908106
