### ISSUE TITLE
サーバーの初期化依頼

### ISSUE THREAD

**Issue by KToshiro** [coderdojo-japan/dojopaas#117]
CoderDojoコザの大城かよ子 です。当該サーバー（IPアドレス：153.120.170.91）の初期化をお願いします。

**Comment by yasulab** [comment]
サーバーが止まってたみたいなのでリブートしました！ 🔧 💨 
もう一度 SSH で繋いでみてもらえませんか？ 🤔💭 (今度は成功するはず...!?)

**Comment by KToshiro** [comment]
接続できました。ありがとうございます。

**Comment by yasulab** [comment]
よかったです...!! d(￣ ￣)✨
