### ISSUE TITLE
サーバーの初期化依頼

### ISSUE THREAD

**Issue by KToshiro** [coderdojo-japan/dojopaas#120]
いつもお世話になっております。
CoderDojo コザの大城です。サーバーにアクセスが出来なくなってしまいました。
当該サーバー（IPアドレス：153.120.170.91）の初期化をお願いします。

**Comment by yasulab** [comment]
サーバーが落ちていたようなので起動させておきました! SSH で繋げられることも確認できました ;) ✅ 

![image](https://user-images.githubusercontent.com/155807/54085700-1941d680-4384-11e9-9291-fc887d618e61.png)
