### ISSUE TITLE
サーバーの初期化依頼

### ISSUE THREAD

**Issue by CoderDojoOfuna** [coderdojo-japan/dojopaas#122]
CoderDojo大船の田中真輔です。当該サーバー（IPアドレス：153.120.166.9）の初期化をお願いします。

**Comment by yasulab** [comment]
依頼ありがとうございます! もしサーバーに接続できない状態であれば、サーバーの初期化ではなくサーバーの再起動で対応することも可能ですが、サーバーの初期化で大丈夫でしょうか? 💭

> **Q. サーバーの接続できなくなった場合はどうすればよいですか?**
> A. [こちらのフォーム](https://github.com/coderdojo-japan/dojopaas/issues/new?title=サーバーの再起動依頼&body=CoderDojo【道場名】の【申請者名】です。当該サーバー（IPアドレス：【xxx.xxx.xxx.xxx】）の初期化をお願いします。&labels=サーバー再起動依頼&assignee=yasulab)から依頼していただけると管理コンソールから当該サーバーを再起動します。 角カッコ `【】` に依頼する道場名、申請者名、IPアドレスをそれぞれ入力してください。

**Comment by CoderDojoOfuna** [comment]
レスありがとうございます！
connection time outが起きているので、再起動依頼にしますね。
