### ISSUE TITLE
サーバーの再起動依頼

### ISSUE THREAD

**Issue by CoderDojoOfuna** [coderdojo-japan/dojopaas#123]
CoderDojo大船の田中真輔です。当該サーバー（IPアドレス：153.120.166.9）の再起動をお願いします。

**Comment by yasulab** [comment]
こちら再起動し、SSH で接続できることを確認しました! 後ほどご確認していただけると幸いです (＞人＜ )✨

![image](https://user-images.githubusercontent.com/155807/58021588-42ca6b80-7b46-11e9-8577-32572ff6eebc.png)

**Comment by CoderDojoOfuna** [comment]
安川さん、確認できました！ありがとうございます！
