### ISSUE TITLE
coderdojo-hiroshimaのサーバ削除をお願いします

### ISSUE THREAD

**Issue by kamera25** [coderdojo-japan/dojopaas#126]
お世話になります。CoderDojo広島の中奥です。

公式Webを別のサービスに移転したため、削除頂けますでしょうか。

なお、鼠屋さんから委任は受けております。

**Comment by yasulab** [comment]
@kamera25 README の下記セクションを参考に Pull Request をお送りいただけると嬉しいです (＞人＜ )✨

📜 README - 3. サーバーが不要になったとき
https://github.com/coderdojo-japan/dojopaas#3-%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC%E3%81%8C%E4%B8%8D%E8%A6%81%E3%81%AB%E3%81%AA%E3%81%A3%E3%81%9F%E3%81%A8%E3%81%8D

**Comment by kamera25** [comment]
https://github.com/coderdojo-japan/dojopaas/pull/127
プルリク作りました！確認お願いします。

**Comment by yasulab** [comment]
#127 で対応したのでこちら Close しますね 😉
