### ISSUE TITLE
instances.csvに表示されない

### ISSUE THREAD

**Issue by ituyama** [coderdojo-japan/dojopaas#129]
三の丸の山野です
三の丸がservers.csvに追加されたことは確認できたのですが
instances.csvに反映されていません
確認していただけないでしょうか

**Comment by yasulab** [comment]
@AnaTofuZ こちらよければ対応お願いできると嬉しいです...!! (＞人＜ )✨

**Comment by yasulab** [comment]
@AnaTofuZ ここら辺が原因っぽい 🐛 👀 💭 
cf. https://travis-ci.org/coderdojo-japan/dojopaas/jobs/562640114#L523-L532

```bash
Copying image for coderdojo-sannomaru...
{ is_fatal: true,
  serial: '1350939e671261ca0ea067d47818eceb',
  status: '409 Conflict',
  error_code: 'disk_is_not_available',
  error_msg: '要求された操作を行えません。ディスクが利用可能な状態ではありません。コピー処理等の完了後に再度お試しください。' }
Copying image for coderdojo-sannomaru...
Start server: 113101230559 for coderdojo-sannomaru.
113101230559 will be destroyed.
(node:5887) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Error: 503: Service Unavailable
(node:5887) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Deleted: 113101230559
undefined
Copying image for coderdojo-sannomaru...
Initialized empty Git repository in /home/travis/build/coderdojo-japan/dojopaas/.git/
fatal: pathspec 'instances.csv' did not match any files
Done. Your build exited with 0.
```

ちなみに SAKURA Cloud にはサーバーは生成されてませんでした 👀 ✅ 

![image](https://user-images.githubusercontent.com/155807/61841177-d44fb400-aece-11e9-8638-3e5057a795b1.png)

**Comment by AnaTofuZ** [comment]
@ituyama @yasulab こんにちは! AnaTofuZです!
今から原因を調査してみますね! 👀 🏃 💨

**Comment by AnaTofuZ** [comment]
現在の実装ではサーバのセットアップ中にエラーが生じた場合サーバのインスタンスを削除しますので、サーバーが生成されなかったかなと思います。

https://github.com/coderdojo-japan/dojopaas/blob/66f3f2657b2796db467377b9649951e6e0abca0d/lib/Server.js#L184-L187

ログを見る限りssh鍵の転送でなにかの問題が発生していそうです。
一旦僕の方で手動で実行してみようと思います。


https://github.com/coderdojo-japan/dojopaas/blob/66f3f2657b2796db467377b9649951e6e0abca0d/lib/Server.js#L130-L177

**Comment by AnaTofuZ** [comment]
とりあえずssh鍵の転送までを実行したところ、こちらでは正常実行が出来ました

**Comment by AnaTofuZ** [comment]
一旦インスタンスを削除し、ssh鍵の転送まで行うようにしましたが、同様のエラーが発生しました。

```
+mumei+anatofuz$ !.                           
./bin/deploy.sh

> dojopaas@1.0.0 deploy /Users/anatofuz/src/github.com/anatofuz/Dotfiles/.sandbox/dojopaas
> node dojopaas.js "--production"

Update startup scripts.
Archive ID:113100422585
Get a list of existing servers.
Create a server for coderdojo-sannomaru.
Create a network interface.
Connect network interface.
Apply packet filter.
Create a disk.
Connect to the disk.
Setup ssh key.
{
  is_fatal: true,
  serial: '1d74155d01a5f8092a83f4dec32eb8f1',
  status: '409 Conflict',
  error_code: 'disk_is_not_available',
  error_msg: '要求された操作を行えません。ディスクが利用可能な状態ではありません。コピー処理等の完了後に再度お試しください。'
}
Copying image for coderdojo-sannomaru...

```

**Comment by ituyama** [comment]
@yasulab @AnaTofuZ 
対応ありがとうございます

**Comment by yasulab** [comment]
@ituyama 先ほどの CI 実行で instances.csv に追記されたことを確認しました 😉 
よければ当該サーバーにアクセスできるかどうかご確認していただけると嬉しいです (＞人＜ )✨

https://github.com/coderdojo-japan/dojopaas/commit/0ec5df7dbb8237421a0aa4dd9d8bdf78b6406a8f#diff-3dfe38357946121c2f0b04a2f80cec54R43

cc/ @AnaTofuZ

**Comment by ituyama** [comment]
@yasulab 
ありがとうございます
ただ、タイムアウトと表示されてしまい、表示されません
