### ISSUE TITLE
サーバーの再起動依頼

### ISSUE THREAD

**Issue by TosIto** [coderdojo-japan/dojopaas#133]
CoderDojo戸田公園の伊藤利昭です。当該サーバー（IPアドレス：153.120.170.166）の初期化をお願いします。cc/ @yasulab

**Comment by yasulab** [comment]
こちら再起動して、SSH で繋がることを確認しました! 👀 ✅ ✨ 

![image](https://user-images.githubusercontent.com/155807/64275288-3694dd80-cf80-11e9-8dfb-fe464d4134a9.png)
