### ISSUE TITLE
再起動依頼

### ISSUE THREAD

**Issue by nakazgawa** [coderdojo-japan/dojopaas#135]
CoderDojo板橋の中津川です。
先ほど申請したサーバーですが、SSHでアクセスしようとしているのですが、エラーも出ず止まっています。

133.242.237.195

よろしくお願いいたします。

**Comment by yasulab** [comment]
再起動しました! ssh も無事にアクセスできそうです 😉 

![image](https://user-images.githubusercontent.com/155807/64275047-abb3e300-cf7f-11e9-9dc9-9385acb70765.png)

**Comment by nakazgawa** [comment]
安川様

ありがとうございました。
無事にログイン出来ました。

中津川
