### ISSUE TITLE
サーバーの再起動依頼

### ISSUE THREAD

**Issue by ituyama** [coderdojo-japan/dojopaas#146]
CoderDojo三の丸の山野です。当該サーバー（IPアドレス：153.127.194.186）の再起動をお願いします。
以前サーバを頂いたときからタイムアウト表示が出て、接続できません...
cc/ @yasulab
[
![Screenshot from 2019-09-22 11-15-07 - 1](https://user-images.githubusercontent.com/42466955/65381375-cb425e00-dd2a-11e9-91d5-7f18aa73cb26.png)
](url)

**Comment by yasulab** [comment]
@AnaTofuZ こちらよければ対応してもらえると嬉しいです (＞人＜ )💦 (スクリプト書いても良いかも？👀💭)

**Comment by AnaTofuZ** [comment]
@ituyama  @yasulab 再起動しました! ubuntuの起動で5分くらい必要なので13:15以降に動いているか確認します..!!

**Comment by AnaTofuZ** [comment]
再起動したんですが、ubuntuのnicが外れているのか、 ipコマンドで該当するIPが確認できませんでした。
コンソールで作業をしてみます

**Comment by AnaTofuZ** [comment]
nicがインターネットと接続していなかった様なので接続しなおして再起動しています...

**Comment by AnaTofuZ** [comment]
NICの再設定を行いましたが接続が確認されませんでした。
今までのログを確認したところ、最初からタイムアウトと表示されていたことから作り直した方が早そうですので、一旦手動で作り直そうと思います

**Comment by AnaTofuZ** [comment]
インストール時にubuntuのkernel errorが出ている気配がある

**Comment by AnaTofuZ** [comment]
サーバー作成後のshut down時にkernel error ( `kernel: BUG: soft lockup - CPU#x` )が出ていましたが強制的に終了後、再起動しました。 コンソールからの `ip a`で指定のIPが設定されていたので大丈夫そうです。

確認をお願いします @ituyama  ( cc @yasulab )

**Comment by ituyama** [comment]
無事起動できました！
ありがとうございます！
@yasulab , @AnaTofuZ

**Comment by yasulab** [comment]
よかったです！😆✨

@AnaTofuZ 対応ありがとうございました〜 (＞人＜ )✨
