### ISSUE TITLE
サーバーの初期化依頼

### ISSUE THREAD

**Issue by coderdojo-kofu** [coderdojo-japan/dojopaas#158]
CoderDojo甲府の福井です。当該サーバー（IPアドレス：【153.120.170.208】）の初期化をお願いします。cc/ @yasulab

**Comment by yasulab** [comment]
こちら初期化しておきました！d(￣ ￣)✨

https://github.com/coderdojo-japan/dojopaas/commit/946f8c2e1e5db6956f758dc189dea2aad9676a7a#diff-3dfe38357946121c2f0b04a2f80cec54R54
