### ISSUE TITLE
サーバーの初期化依頼

### ISSUE THREAD

**Issue by zyasuda** [coderdojo-japan/dojopaas#163]
CoderDojo【札幌東】の【安田圭吾】です。当該サーバー（IPアドレス：【153.127.197.155】）の初期化をお願いします。cc/ @yasulab

**Comment by yasulab** [comment]
こちらサーバーを初期化しました! 🛠💨✨

**Comment by zyasuda** [comment]
ありがとうございました。
すみません、GitHubの使い方もわからないものですが、
以前お手数をお掛けした@manzyunさんの公開鍵を変更し、新たにマイクラサーバーを立ち上げたいと思っております。

先日servers.csvの説明と公開鍵を変更しようとしてPRをしたのですが、どうやら変更されないようです。
おそらく先にservers.csvを変更してから初期化をお願いすべきだったのでは？と思っています。
素人の書き込みで大変申し訳ありませんが、新しい公開鍵でSSHログインできるまでの手順をご教授いただければありがたいです。
よろしくお願いします。（Closeしてるから見れないかな？）

**Comment by manzyun** [comment]
どもども、お騒がせしております。僕です。その節は大変ご迷惑おかけしました :bow: 

@zyasuda さん、恐縮なのですがGitHubのPRページのアドレスか、PRの `#` で始まる番号って分かります？

このリポジトリのPR（Pull Requests）のページで、zyasudaさんが作ったPRが僕が2分で検索掛けた限りでは見つからなかったんですよ😥

もし見つかったらコメントでお伝えいただけると、 @yasulab さんも対応しやすいかなと思いました。

# P.S.
GitそのものにはPull Request機能はなく、あくまでGitHubのページから、
「このブランチを引っ張ってください、よろしくおねがいします！」
と申請する形になります。ご存知でしたらすみません :bow:

**Comment by zyasuda** [comment]
manzyunさん、ありがとうございます。
（ここで話しないで、yasulabさんを巻き込むまでもないのかもしれませんが、、）

> PRページのアドレスか、PRの # で始まる番号
すでにわかりません。私のActivityにも記録がありませんでした。何で？（実は2回目）

いずれにしてもservers.csvの公開鍵を変更しないとこちらでSSHログインできないと思うのですが、、
（初期化したけど、今でもmanzyunさん、旧インスタンスにログインできるの？
今回の新しいサーバーはmanzyunさんにお願いするつもりはありませんが）

如何にお願いして良いものやら…
それがわかれば、再度変更内容をお送りすることはできます、、

**Comment by manzyun** [comment]
> いずれにしてもservers.csvの公開鍵を変更しないとこちらでSSHログインできないと思うのですが、、
> (中略）
> 如何にお願いして良いものやら…
> それがわかれば、再度変更内容をお送りすることはできます、、

ふと、
「当人は確かに作業している」
ということだったので、このリポジトリのフォークから @zyasuda さんのリポジトリをたどり、そのなかのブランチでそれっぽいものを見つけました（日付も2日前なのでこれな気がする） 🧐

[Commit hash: e08c997 - zyasuda / dojopaas - GitHub](https://github.com/zyasuda/dojopaas/commit/e08c997eaf98997c03639e0eec3fd8e7352b4c0a)

ということで安田チャンピオン、準備は整ってました！ :raised_hands: 

# この後の手順
後はお手数ですが、また僕が勝手にやると安田チャンピオンのの肝を冷やしたり……と酷い事になると思い自重してPR申請を完了する手前までの手順を画像付きで説明いたします 😅

_少しでも作業時の緊張感を抜きたかったので落書きしました。おふざけが過ぎてるかもしれませんが。_

## 1. `zyasuda / dojopaas` リポジトリにアクセス
まずは [安田チャンピオンの `dojopaas` リポジトリ（プロジェクト）](https://github.com/zyasuda/dojopaas)にアクセスします。
![今回は分流から本流なので。](https://user-images.githubusercontent.com/461212/84008654-17165f80-a9ad-11ea-9267-3988fcfe2df9.png)

## 2. `Pull Requests` のページに移って `New pull request` のボタンを押して申請フォームへ
次にタブ状になっているリポジトリメニューから `Pull Requests` をクリックします。
そして下図の様なページに遷移しますので、  
「緑色で表示されているから判るがな！」
と思われるかもしれませんが、 `New pull request` のボタンを押して申請フォームへ遷移します。
![ページ遷移後の表示を見ればひと目で判るかもですが。](https://user-images.githubusercontent.com/461212/84009108-c3f0dc80-a9ad-11ea-899e-5e6c07f82c47.png)

## 3. Pull Request先とPull Requestするブランチの設定
すると少しややこしいページに移ります。この過程ではPull Requestを送るリポジトリとブランチの指定、そして申請したい編集内容が記録されているブランチを指定します。
![申請する先のリポジトリとブランチ、そして申請するブランチを要チェックですよ！](https://user-images.githubusercontent.com/461212/84009558-6a3ce200-a9ae-11ea-86da-38942d74c7df.png)

とてもうるさく落書きしましたが、ここで間違えても別のところに申請が行くだけなので落書きどおり血眼になってまで確認しなくてもいいかもしれません。

## 4. 申請内容がのプレビューが表示されるので念の為変更内容を確認
いつもの僕だと「パッ」と変更内容を見て下図の落書きどおりに申請の手順を進めるところですが（慣れは怖いですね）、プレビューでは申請先のブランチと申請するブランチの差分を抽出して表示してくれます。
![for_champion_yasuda_3](https://user-images.githubusercontent.com/461212/84010532-c05e5500-a9af-11ea-8143-0ebc427ff71d.png)

必要以上の変更がないか・必要な変更がされているかを確認して、  
「お願いしまァァァァァす！」  
と、某「夏場に先輩の家に泊まり込みで遊びに行ったら、うっかり全世界を天秤にかけた戦いをすることになってしまう」アニメ映画の熱いシーンの様に……は大げさですね。緑の `Create pull request` を押してください。

以上がちょっと解説の必要な部分だと思いました。この後はテキストエリアが出てきて申請内容の概要を書く工程があると思いますが、[このリポジトリの「Pull Request」のサンプル](https://github.com/coderdojo-japan/dojopaas/pull/1)をご覧いただければと思います。

以上、長々と失礼しました。

<details>
<summary>調査過程</summary>

1. 安田チャンピオンがGitもしくはGitHub上で操作したものの、本流リポジトリ（ここ）へプルリクエストが投げられていないものと想定 🙄
2. 安田チャンピオンは僕のようにホイホイ本流リポジトリを `clone` しないと思ったのでForkを確認 👈
3. あった。直近のコミット履歴を確認。予想通り 😏

</details>

<details>
<summary> オフ・トピックス。大人気ない事情なので折りたたみ</summary>

> （初期化したけど、今でもmanzyunさん、旧インスタンスにログインできるの？
> 今回の新しいサーバーはmanzyunさんにお願いするつもりはありませんが）

その件に関しては、 @johnny-shaman さんに管理者権限を与えた数週間後に不可能になってます。
当人に確認したところ、私の管理者権限をあえて消したとのことでした。
</details>
