### ISSUE TITLE
サーバーの削除依頼

### ISSUE THREAD

**Issue by Hajime0512** [coderdojo-japan/dojopaas#174]
CoderDojo Ishigakiの浦添一です。当該サーバー（IPアドレス：153.125.131.106）の削除をお願いします。(秘密鍵の紛失により、サーバーを立て直したいため) cc/ @yasulab

**Comment by yasulab** [comment]
@Hajime0512 了解です！初期化時に新しい公開鍵が必要なので、csv の該当行を更新する PR を送っていただけると嬉しいです (＞人＜ )✨

**Comment by Hajime0512** [comment]
新しい公開鍵のPull Requestを送信しました～
よろしくお願いします！

**Comment by yasulab** [comment]
@Hajime0512 #175 をマージしました！後ほど CI 経由でサーバーも順次生成されていきますので、確認できましたら本 Issue を Close していただければ...!! (＞人＜ )✨

**Comment by Hajime0512** [comment]
了解です！
確認次第Closeしますね

**Comment by yasulab** [comment]
サーバー生成されたようです！(๑•̀ㅂ•́)و✨ https://github.com/coderdojo-japan/dojopaas/commit/453c6b26d28fe2150aca47ae12d6454abcc0b6d5

**Comment by Hajime0512** [comment]
接続できました、ありがとうございます！
Closeしますね
