### ISSUE TITLE
サーバーの再起動依頼

### ISSUE THREAD

**Issue by coderDojo-matsuyama-ehime** [coderdojo-japan/dojopaas#178]
CoderDojo松山の 佐伯淳 です。当該サーバー（IPアドレス： 153.125.131.53 ）の再起動をお願いします。cc/ @yasulab
OSのバージョンアップ作業中に外部との接続ができなくなりました。
現状
〇DNSでの名前解決ができない digで解決できない
〇IPアドレス直接でも、外部にたどり着かない。
〇SSHは接続可能です。

再起動でどうなるかわかりません、もし再起動でどうにもならないのであれば初期化も視野に入れたく思います。
お手数おかけしますが、よろしくお願いいたします。

**Comment by yasulab** [comment]
#180 で対応したので、こちら Close しますね 😌
