### ISSUE TITLE
CSVのフォーマットを間違った場合の対処方法

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/dojopaas#18]
誤ってマージしてしまった場合、どうするか考えたい🤔

cc/ @NorifumiOgawa @miya0001 

## 失敗したケース

- CoderDojo 嘉手納用のサーバーを申請します。 #16
- カンマ抜けの修正 #17 

## 対応案

- CSVフォーマットをテストして、失敗した場合はサーバーを生成しない?

**Comment by yasulab** [comment]
## ワークアラウンドな対応

これで行けそうなきがするので、ちょっと試してみます

1. コントロールパネルからサーバーをシャットダウン
2. コントロールパネルからサーバーを削除
3. CSVから当該業を削除
4. もう一回、PRを送り直してもらう

**Comment by yasulab** [comment]
@NorifumiOgawa ちょっと上の方法で作業をしてみました。もう一回PR送ってもらってもいいですかね?

**Comment by yasulab** [comment]
ワークアラウンドな方法で対応できるかな...? 🤔
https://github.com/coderdojo-japan/dojopaas/pull/19

**Comment by yasulab** [comment]
お、この方法でなんとかなりました! 🔧 💨 

https://github.com/coderdojo-japan/dojopaas/commit/9421c48d90f8e2caf982fed931e5b5b5728b6561

今回は運用で対応していますが、理想的にはテストなどで対応した方が良いと思うので、この Issue は閉じずにこのままにしておきますね ;)

**Comment by miya0001** [comment]
昨日、CSVの列の数と簡単な正規表現のチェックをするようにTravis CIで仕込みました。
https://github.com/coderdojo-japan/dojopaas/blob/master/test/test-csv.js

それでもマージはできてしまうので、それを防ぐために以下のようにGitHubで設定してもらうと、問題が治らないとマージできなくなります。
![](https://www.evernote.com/l/ABUDBwSWPndKTK69SPxBcxzJKbQcrwpoaCkB/image.png)

ただ、この設定をするための権限がぼくになかったので @yasulab さんでやってもらっていいですか？

テストがコケたときのプルリクエストに対する修正はご本人でもコミッターでも可能です。

**Comment by yasulab** [comment]
設定しました! これで対応できたと思うので、この Issue は Close しちゃいますね ;)

<img width="1055" alt="screen shot 2017-07-22 at 14 19 50" src="https://user-images.githubusercontent.com/155807/28488615-e59a4a22-6ee8-11e7-8d6c-b657efcf8f6f.png">

**Comment by miya0001** [comment]
ダメなCSVフォーマットでプルリクが来ると以下のような感じになります。
![](https://www.evernote.com/l/ABX5wlFFE1VC5pD8ucWQiqWwgECqPHIOHYcB/image.png)

これでもマージはできてしまうので、気持ち悪ければ `Include administrators` にチェックをいれるとそれもできなくなります。

**Comment by yasulab** [comment]
@miya0001 補足ありがとうございます! 😸

赤文字になって注意喚起はできていますし、仕様変更などに伴ってテストの方が間違っているケースもありうる思うので、とりあえずはこのままで良いかなと思いました ;)
