### ISSUE TITLE
サーバーの初期化依頼

### ISSUE THREAD

**Issue by coderDojo-matsuyama-ehime** [coderdojo-japan/dojopaas#180]
CoderDojo松山の佐伯淳です。当該サーバー（IPアドレス：153.125.131.53）の初期化をお願いします。cc/ @yasulab
先日再起動の連絡させていただきましたが、OSアップデートだけですので初期化いただいた方が確実かと思います。
お手数おかけしますがよろしくお願いいたします。

なお、構成不明で仮想化されていると想像していましたのでアップデートしていましたが、NGであれば控えます。いかがでしょうか？

**Comment by yasulab** [comment]
こちら初期化しておきました！後ほどご確認いただけると幸いです (＞人＜ )✨

> なお、構成不明で仮想化されていると想像していました

使っているサービスは「さくらのクラウド」となりますので、構成は公式ページをご参照ください 🙏 https://cloud.sakura.ad.jp/

さくらのクラウドでインスタンスを立ち上げ、下記スクリプトを実行した状態から始まります。
https://github.com/coderdojo-japan/dojopaas/blob/master/startup-scripts/112900928939

アップデートが NG かどうかは「さくらのクラウド」の仕様によるので、上記公式ページをご参照していただくのが良さそうです! :eyes: ✅

**Comment by coderDojo-matsuyama-ehime** [comment]
ありがとうございました。お手数おかけして申し訳ありません。

**Comment by coderDojo-matsuyama-ehime** [comment]
初期化後のIPアドレス教えていただいてよろしいでしょうか。
初期化後、IP変更になっていると思います。接続できませんでした。
https://github.com/coderdojo-japan/dojopaas/blob/gh-pages/instances.csv

**Comment by yasulab** [comment]
お、CI が止まってそうですね。少々お待ちください...!! 👀💨
https://travis-ci.org/github/coderdojo-japan/dojopaas/builds/772408832#L988

**Comment by coderDojo-matsuyama-ehime** [comment]
了解です。
今から出るので、お時間空いたタイミングで良いですよ。

**Comment by yasulab** [comment]
こちら生成されました！後ほどご確認いただければ...!! (＞人＜ )✨
https://github.com/coderdojo-japan/dojopaas/commit/c4f4ce0246d0672b5c5dfb684b9c8daa88353410#diff-a53981e8f7ae450731a2fc70015616034947864b09384f97757b3376e92c6f02R63

**Comment by coderDojo-matsuyama-ehime** [comment]
戻ってきて今確認してみました。ちゃんと利用できています。ありがとうございました。
