### ISSUE TITLE
サーバーの初期化依頼

### ISSUE THREAD

**Issue by coderdojo-kurume** [coderdojo-japan/dojopaas#182]
CoderDojo【久留米】の【sugiyama misuzu】です。当該サーバーの初期化をお願いします。

**Comment by yasulab** [comment]
対応しました！後ほどアクセスしてみてもらえると嬉しいです！(＞人＜ )✨
https://github.com/coderdojo-japan/dojopaas/commit/be3fda058ad5dc4db4f54dc77a22a99bfeb66409

**Comment by coderdojo-kurume** [comment]
対応ありがとうございました！無事接続できました！
