### ISSUE TITLE
サーバーの削除依頼

### ISSUE THREAD

**Issue by u-akira** [coderdojo-japan/dojopaas#194]
CoderDojo香椎の宇都木（うつき）です。当該サーバー（IPアドレス：【133.242.237.34】）の削除をお願いします。cc/ @yasulab

代表を交代したので、削除後に改めて申請します。

**Comment by yasulab** [comment]
こちら #195 で対応しました！削除依頼のご連絡ありがとうございます (＞人＜ )✨
