### ISSUE TITLE
サーバーの削除依頼

### ISSUE THREAD

**Issue by u-akira** [coderdojo-japan/dojopaas#198]
CoderDojo香椎の宇都木です。当該サーバー（IPアドレス：133.242.224.96）の削除をお願いします。
すみません。申請した秘密鍵のパスフレーズを忘れてしまったので、一度サーバを削除します。
cc/ @yasulab

**Comment by yasulab** [comment]
@u-akira README に具体例を記載しておきましたので、README の下記セクションを参考にしながら PR を送っていただけると幸いです (＞人＜ )✨

3. サーバーが不要になったとき - README
https://github.com/coderdojo-japan/dojopaas#3-%E3%82%B5%E3%83%BC%E3%83%90%E3%83%BC%E3%81%8C%E4%B8%8D%E8%A6%81%E3%81%AB%E3%81%AA%E3%81%A3%E3%81%9F%E3%81%A8%E3%81%8D

**Comment by u-akira** [comment]
PRを作成するんでしたね。すみません。
