### ISSUE TITLE
サーバーの再起動依頼

### ISSUE THREAD

**Issue by tamagokakegohann** [coderdojo-japan/dojopaas#209]
CoderDojo【小平】の【和田　拓也】です。当該サーバー（IPアドレス：【153.125.128.236】）の初期化をお願いします。cc/ @yasulab

**Comment by yasulab** [comment]
サーバーを初期化しました! IP アドレスも変更されたので、README の https://github.com/coderdojo-japan/dojopaas#2-ssh%E3%81%AE%E6%8E%A5%E7%B6%9A%E6%96%B9%E6%B3%95 から再度 IP アドレスを確認してみていただければ！(＞人＜ )✨
