### ISSUE TITLE
サーバーの初期化依頼

### ISSUE THREAD

**Issue by naopontan** [coderdojo-japan/dojopaas#222]
CoderDojo【coderdojo-naha】の【高江洲】です。当該サーバー（IPアドレス：【133.242.230.237】）の初期化をお願いします。cc/ @yasulab @Yuppymam 

よろしくお願いします😺 🙏

**Comment by yasulab** [comment]
@naopontan  こちら対応しました！(๑•̀ㅂ•́)و✨

**Comment by naopontan** [comment]
@yasulab 
ご無沙汰してます! 😸  
こちら確認できました。対応頂きありがとうございました (≧∇≦)b
