### ISSUE TITLE
サーバーの初期化依頼

### ISSUE THREAD

**Issue by IchiroKano** [coderdojo-japan/dojopaas#230]
CoderDojo【青梅】の【鹿野市郎】です。当該サーバー（IPアドレス：【153.125.147.19】）の初期化をお願いします。cc/ @yasulab

**Comment by IchiroKano** [comment]
素早い対応ありがとうございました。
問題なく再ログインすることができました！

**Comment by yasulab** [comment]
いえいえ! 無事に初期化できたようでよかったです! 😆✨
