### ISSUE TITLE
サーバーの初期化依頼

### ISSUE THREAD

**Issue by coderdojo-sendaiwakabayashi** [coderdojo-japan/dojopaas#239]
CoderDojo【仙台若林】の【伊深】です。当該サーバー（IPアドレス：【153.125.128.236】）の初期化をお願いします。cc/ @yasulab 

```
特段設定変更したわけではないのですが、sshの応答がなくなっていました。
お手数おかけしますが、回復のため、初期化をお願いします。
```

**Comment by yasulab** [comment]
こちら対応しました！(๑•̀ㅂ•́)و✨

**Comment by coderdojo-sendaiwakabayashi** [comment]
@yasulab
素早い対応ありがとうございます。

残念ながらタイムアウトでまだ接続できません。
> coderdojo-sendaiwakabayashi	153.125.128.236
```
pi@raspberrypi:~ $ ssh ubuntu@153.125.128.236
ssh: connect to host 153.125.128.236 port 22: Connection timed out
```

最終コミットが２週間前のようで初期化の前後でinstances.csvの
IPアドレスが変わってないので、もしかして、別のファイルを確認する必要がありますか？
https://github.com/coderdojo-japan/dojopaas/commits/gh-pages/instances.csv


接続元のNWの経路などの問題ではなさそうです。
隣のcoderdojo-kyotoshijo	（153.127.218.145）さんにアクセスした結果です。
```
pi@raspberrypi:~ $ ssh ubuntu@153.127.218.145
The authenticity of host '153.127.218.145 (153.127.218.145)' can't be established.
ECDSA key fingerprint is SHA256:yMnV9qBS37l3CDUmyflGXYHJPGijLYSw+3akWAnboKU.
Are you sure you want to continue connecting (yes/no)? ^C
```

お手数おかけしますが、よろしくお願いします。

**Comment by yasulab** [comment]
こちら CI がうまく動いてなかったようですね >< 💦 

- Attempt 1: https://github.com/coderdojo-japan/dojopaas/actions/runs/10764548091/job/29847549832
- Attempt 2: https://github.com/coderdojo-japan/dojopaas/actions/runs/10764548091/job/29871253146

先ほど Re-run したので再度ご確認いただけると幸いです! (＞人＜ )✨


<img width="1722" alt="image" src="https://github.com/user-attachments/assets/a81932b2-b947-423a-9cd0-eed9753fbb90">

**Comment by coderdojo-sendaiwakabayashi** [comment]
対応ありがとうございます！
今度は無事ログインできました。解決です！

```
ubuntu@ubuntu:~$ uptime 
 21:26:36 up 16 min,  1 user,  load average: 0.06, 0.02, 0.00
 ```
ちなみに、instances.csvは最終行に変わったものの、IPアドレスは変わらないようでした。
