### ISSUE TITLE
Minecraft インストール済みにする Startup Script

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/dojopaas#28]
Minecraft インストール済みのサーバーを生成する Startup Script を作りたい。

ただし、デフォルトで用意している次のスペックだと動かない可能性が高そう (要調査) 👀 

> - CPU: 1コア
> - メモリ: 1GB
> - ディスク: 20GB

cf. https://github.com/coderdojo-japan/dojopaas/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by miya0001** [comment]
ディスクに関してなんですが、最低で20GBでその次に選べるサイズは40GBなんですよね。
ご提供いただいている全体の量がちょうど20GBx100台なので結果的にディスクのサイズは固定にしないといけないんです。

**Comment by yasulab** [comment]
> 最低で20GBでその次に選べるサイズは40GBなんですよね。

なるほど。さくらインターネットからの説明だと、コントロールパネルから特定のサーバーのディスクサイズだけを拡張できるという話でした。なので、(少なくとも手動で操作する分には) マインクラフト用のサーバーだけサイズを大きくすること自体はできそうですが、公平性にやや欠けるのが課題かなぁと考えています🤔

**Comment by miya0001** [comment]
* メモリ: 総合計で100GB
  * ディスク: 総合計で2048GB

とのことで、メモリも1GB単位でしか指定できないんですよね。
なのでメモリ、ディスクそれぞれパワーアップするたびにマシンが1台減る感じです。

Mincraft用のすごく高性能な共有サーバーを作るとか。

**Comment by miya0001** [comment]
マイクラ用のサーバーって何かアップロードしたりするんですかね？普通に遊ぶだけじゃない？
そもそもマイクラ用のサーバーというものについてよくわかってなくてすいません。

**Comment by miya0001** [comment]
無理っぽいですね。笑

![](https://www.evernote.com/l/ABUCXWWfwwxCfKwJl_QMwPOCbNmcJc2ENq4B/image.png)

**Comment by miya0001** [comment]
ウェブサーバーはバーチャルホストで、マイクラサーバーだけを49台提供するとか。。。

**Comment by yasulab** [comment]
> http://minecraft.gamepedia.com/Server/Requirements

ディスクサイズは大丈夫そうですが、メモリが2GB〜8GB... orz

**Comment by miya0001** [comment]
あっ、あとDojo開催日に使い捨てのハイスペックなマイクラサーバーを立ち上げれる仕組みをつくるとか。
こいつは数日後とかに自然消滅するみたいな。

**Comment by miya0001** [comment]
Slackで "/run-minecraft <公開鍵>" って叩いたらサーバーが起動するとかしたら面白そう！

**Comment by yasulab** [comment]
> マイクラ用のサーバーって何かアップロードしたりするんですかね？普通に遊ぶだけじゃない？

僕が把握している限りだと、例えば [8x9クラフト](http://wiki.craft.8x9.jp/wiki/Setup/ja)や[ComputerCraft](http://hevohevo.hatenablog.com/entry/cc_programs)のようなMODをサーバーに追加して、当日マインクラフトの世界でプログラミングする、みたいユースケースかなと考えています。

なので、次のようなアイデアは結構効果的かもしれません🤔

> - Mincraft用のすごく高性能な共有サーバーを作る
> - Dojo開催日に使い捨てのハイスペックなマイクラサーバーを立ち上げれる仕組みをつくる

より詳細な利用ケースについては、使いたい道場の方に聞いて見たいですね。Facebook グループの方でこちらの Issue についてリンク貼っておきます! 😄

**Comment by miya0001** [comment]
Slackのコマンドで起動できるようにしましょう！w
そして24時間後に自動終了。

**Comment by miya0001** [comment]
http://qiita.com/t-mimura/items/d6541ec596bdebea5a7b

**Comment by yasulab** [comment]
CoderDojo 関係者の詳しそうな人にメンションさせていただきました。どなたか降臨してくれると嬉しいな... 🙏

**Comment by yasulab** [comment]
最初からマイクラ用の共有リソースを確保するという方法もありかもしれないですね。Webサーバーとしての利用申請が増えていくと、そのうち「リソースが足りなくて立ち上げらない」というケースが考えられるかなと思いました🤔💭

**Comment by miya0001** [comment]
メモリとディスクの総量の管理は簡単なので、あらかじめ8GBx5台分とか用意しておくといいかも。
要はウェブサーバーとしては予約分を引いたものだけをマックスにしつつ、たとえばWordPress専用の共有サーバーを作っておくとか。
そうするとサーバーのめんどうをみることはできないけどサイトだけほしいというケースにも低コストで対応できそう。

**Comment by miya0001** [comment]
共有サーバーは、

* WordPress専用のバーチャルホスト
* プラグインは指定したものだけがプリインストール。
* テーマはデフォルトのテーマのみ
* SSHやFTPのアカウントはわたさない。
* ドメインは *.coderdojo.jp
* SSL & HTTP/2 標準装備

って感じかなーと。たとえばWordPressの公式イベントのWordCampは同じような仕組みでして、見た目の部分はCSSだけで対応しています。なので意外とそれなりのものが作れるはず。

一方でWordPressのアップデートとかは自動化してこちらでまとめて面倒見るみたいな。

**Comment by yasulab** [comment]
WordPress の話と Minecraft の話が混ざると内容がブレそうなので、WordPress の共有サーバーについては #27 の方で話をまとめられると嬉しいです 🙏 💦 僕の方で #27 に転記しておきますね 📝 💨

**Comment by yokmama** [comment]
マイクラのサーバーをCoderDojo全部で一つは可能だとおもいます。
その場合、ログインできるのは忍者だけに限定するということもできます。
これは、忍者のアカウントを登録制にして、登録されている人以外はログインできないようにする仕組みが公式のマインクラフトサーバーにあるからです。

こうすれば、悪質なあらしの対策はできるとおもいます。

とはいえ、故意ではないことからのトラブルが実は多いです。
間違って壊してしまったりとか、ついかっとなってやってしまったとか。
そういうことの解決にもプラグイン（マインクラフトのサーバーを改変するためのソフト）をいれたほうがよいです。

ほかにもいろいろなModやプラグインがあります。
これらは、遊びたい子供の要求にあわせていれる必要がでてくるとおもいますが。
Modやプラグインには相性があるのでなんでもかんでもいれるといわけにはいかないです、

全国の忍者たちの要望にあわせていれるのは非常に難しいとおもいます。
そのため、基本的には、運営側が一方的にいれるModを選定していれるしかないとおもいます。

それから、サーバーに必要な容量ですが、
サーバーの起動には、２Gは最低いるといってますが、２Gだと２，３人で遊ぶながらいいですが、それ以上になると厳しいとおもいます。
マインクラフトのワールドは、自動生成です。そのため、最初は小さいのですが、プレイヤーがそのなかであるきまわるとどんどん生成されてどんどん広くなっていきます、すうするとその分だけディスクの使用量はふえますし、またプレイヤーが分散するとそのぶんだけメモリにつまれるデータもふえます、だいたい、２G+８G（プレイヤー、マップデータ）だと考えるといいとおもいます。

プラグインによって、メモリの使用量はかわってくるので、運用してみて重たいならふやしていくっていうのがベストだとおもいます。

**Comment by yasulab** [comment]
> だいたい、２G+８G（プレイヤー、マップデータ）だと考えるといい

情報ありがとうございます! 少なくとも１道場１台は現実的ではなさそうですね 😅 

> 全国の忍者たちの要望にあわせていれるのは非常に難しいとおもいます。
> そのため、基本的には、運営側が一方的にいれるModを選定していれるしかないとおもいます。

さくらサーバーのアカウント管理チームと同じ要領で、マイクラサーバーの運用チームというのを作って、そこでやりとりできるようになると良いのかなぁ... とぼんやり考えています 🤔💭 (cc/ @tkc49 )

**Comment by miya0001** [comment]
@yokmama @yasulab 

このPaaSのシステムとは別にマイクラ用の共有サーバーを立てておく感じですね。
この場合独自のModとかはインストールできない感じになると思うのですが、そういうマイクラプログラミングの練習用の環境は別に必要という理解であってます？

**Comment by miya0001** [comment]
みんなが好き勝手にいろいろアップするようなマイクラプログラミングの環境に適していないというか。

**Comment by yasulab** [comment]
そうですね、現時点では、もしやるとしても、PaaS システムと繋げる必要性はなさそうなので、切り離して運用する形でも良いかなと感じています🤔

ただ決定というわけではないので、とりあえずこの Issue はまだ残しておいてもらえると助かります 🙏

**Comment by yasulab** [comment]
メモ: magikcraft の開発者はCoderDojo向けにマイクラサーバーを提供している

cf. magikcraft
https://www.magikcraft.io/

**Comment by yasulab** [comment]
## メモ

CoderDojo 向けにマイクラサーバーを提供しているスポンサー企業がある。実は `ja.open.magikcraft.io` が既に用意されている。マイクラ使いたい人はこちらを使っていただいて、さくらインターネットからのサーバーは[共通のスペック](https://github.com/coderdojo-japan/dojopaas/issues/28#issue-244886282)内で自由に使ってもらうのが良さそう。

> Hi Takashi! You should now be able to manage your ja.open.magikcraft.io server here:
> https://play.magikcraft.io/servers

**Comment by yasulab** [comment]
こちら、 @tkc49 さんとの話し合いで、「CoderDojo Japan 側では特定のアプリケーションのための共有サーバーは作らず、各道場へのインフラ提供に専念しよう」ということにしました。理由としては、次の通りになります。

- 特定のアプリケーションをOKすることは、他の特定のアプリケーションをOKにしないことになる
   - 例: ComputerCraft は :ok: で、なぜ 8x9Craft じゃダメなのか? 
   - 例: xxx という MOD は :ok: で、なぜ ooo という MOD は :ng: なのか? etc.
   - 「何がOKで何がNG」というのを決めるのにも、とても時間がかかりそうだと感じています... 😓 
- アプリケーションについては、アプリケーションを提供する側にスポンサードしてもらう形を推奨したい
   - 例: Mgikcraft for CoderDojo: https://start.magikcraft.io/#Magikcraft-for-CoderDojo
   - こうすることで、アプリケーションを提供してくれるスポンサーの増加にも繋がりやすくなる
- dojopaas ではインフラ提供 (+ スタートアップスクリプト) 程度までに押さえておいて、「スペックを増やしたい」という要望があれば、各道場が個別にさくらインターネットさんとやりとりする形でまずは運用したい

 @miya0001 上記の理由で、一旦はこの Issue を Close しようかなと思うのですが、いかがでしょうか? 🤔

**Comment by miya0001** [comment]
はい、閉じるのは異存ないです。

ただひとつ誤解があるようですが、特定のアプリケーションをOKとかNGとかではなく、いろんなのを簡単にセットアップできるようにしてプログラミングの勉強に集中できるようにしてあげたいなーと思ったのが僕の目的です。
プログラミングの勉強をするのにさらに難しいインフラを用意しないといけないという太古からの問題を解決してあげたいなと。

僕の妄想では必要と思った人がシェルスクリプトなりなんなりを作るはずなので、それを順次取り込んだらいいと思ってました。CoderDojoのリポジトリにいろんなインストーラのプロジェクトが増えるといいかなと。なので特定の何かを選ぶとかではなくランダムに増えたらいいんじゃないかと思った次第です。

**そんなわけで「何かをいらない」っていう判断はする必要ないんじゃないかなとは思っています。**
(大事なので太字で。これは手伝いたいと思ってる人に対して無駄にハードルを上げるだけだと思います。現実にはそういうの人がいないってことかな。。。汗）

> アプリケーションについては、アプリケーションを提供する側にスポンサードしてもらう形を推奨したい
ちなみにこのほうがさらにOKとかNGの選択が大変なような。。。笑

まあ、マイクラはスペック的に難しいみたいなので、そういう意味で無理かなとは思ってましたし、誰かがやるかなと思ってたので誰もやらないなら閉じていただいても大丈夫です！

**Comment by yasulab** [comment]
@miya0001 説明が足りずすみません、認識にズレが生じているようですね 💦 個人的には全く同じことを主張していて、特に誤解は無いように感じました ><

僕としては書きに述べたように、インストーラが増えることはとても良いことだと思います! 😸 

> dojopaas ではインフラ提供 (+ スタートアップスクリプト)

一方で、 **特定のアプリケーションを動かすために大きな共有サーバーを作成するのは一旦 pending にしたい** と考えています。この Issue のタイトルとズレているので、そこが誤解の元になっているのかもしれないですね 😅 

言い換えると、Minecraftのスタートアップスクリプトを作るのは全く問題ないですが、「マイクラが動かないので共有サーバーを作る」というのは、今はやらないようにしたい、といった内容になります 🙇

**Comment by tkc49** [comment]
安川さんとの話では、前提があってこういう話しの流れになりました^^

[前提]
さくらインターネットさんから提供して頂けるリソースには限りがある。
現在のところ１Dojo、メモリー１Gよねーって話になっている。
Minecraftはメモリー１Gでは無理。

その中で◯◯については特別メモリーを増やす、◯◯についてはメモリーを増やさないという検討はちと大変かなと思いました。

> 僕の妄想では必要と思った人がシェルスクリプトなりなんなりを作るはずなので、それを順次取り込んだらいいと思ってました。CoderDojoのリポジトリにいろんなインストーラのプロジェクトが増えるといいかなと。なので特定の何かを選ぶとかではなくランダムに増えたらいいんじゃないかと思った次第です。

これについては僕もその方が良いと思います！！
なので、今回の件で言えばメモリー１Gの範囲であれば、色んなインストーラーがあると良いなと思います。

１G範囲内であればっていう視点では話しをしてなかったので、１Gの範囲であれば
「「何かをいらない」っていう判断はする必要ない」という点には、そうだなーと思います！！
※ 当然、オープンソースだったり、CoderDojoへ無償提供してもらえてるものに限るとは思いますが。

**Comment by miya0001** [comment]
なるほど！いろいろ便利なのが出てくるといいですね！

**Comment by miya0001** [comment]
共有サーバーの件は理解しました！まあプログラミングの勉強につかいにくいただの遊び場だったらなんだかなーって感じですもんね。

**Comment by yasulab** [comment]
ありがとうございます! 😆 細谷さんが[３行でうまくまとめてくれました](https://github.com/coderdojo-japan/dojopaas/issues/28#issuecomment-318235693)ので、一旦はこちらの理由でMinecraftのスタートアップの作成は Pending にしようと思いますね。

> [前提]
> さくらインターネットさんから提供して頂けるリソースには限りがある。
> 現在のところ１Dojo、メモリー１Gよねーって話になっている。
> Minecraftはメモリー１Gでは無理。

もし何らかの方法で実現可能になったら、その際に Re-open する形で進められたらですね ;)
