### ISSUE TITLE
生成したサーバーの連絡方法

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/dojopaas#3]
## アイデア:

> アカウントの連絡方法はgh-pagesにサーバーの一覧のウェブページをコミットしておいて、そこにサーバーのIPのリストを並べちゃうとかどうですかね？
> 
> プルリクがマージされたらサーバーの一覧がここにあるから、自分で申請したサーバーのIPを見てそこにSSHで接続してーみたいな。出先でもマージのボタンを押すだけで話がおわるかなと。

**Comment by miya0001** [comment]
gh-pagesブランチにサーバーのリストのHTMLをTravis CIからpushするようにしたんですが、リダイレクトされてしまって見れないです。。。

https://coderdojo-japan.github.io/dojopaas/

これ、GitHub側でなにか対処方法があるきがするんですが、現状はまだ調べきっていません。

**Comment by miya0001** [comment]
よく考えたらGitHubはいい感じでCSVをフォーマットしてくれるので、プルリクがマージされたら以下のURLを見てねという感じでREADMEに記載しました。
https://github.com/coderdojo-japan/dojopaas/blob/gh-pages/instances.csv

**Comment by yasulab** [comment]
> よく考えたらGitHubはいい感じでCSVをフォーマットしてくれるので、プルリクがマージされたら以下のURLを見てねという感じでREADMEに記載しました。
> https://github.com/coderdojo-japan/dojopaas/blob/gh-pages/instances.csv

ありがとうございます! 僕もまずはその運用で大丈夫だと思います! 😸👌
