### ISSUE TITLE
デフォルトのポートが全開放しているので、ドキュメントにしたがって閉じる

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/dojopaas#4]
## デフォルトのポート

![開放されているポート一覧](https://www.evernote.com/l/ABUdwRPelzlF65kk352EvdIahtQqzDP2MmcB/image.png)

## 対策

> SSH（tcp/22）、HTTP（tcp/80）、一般通信用ポート（tcp・udp/1024～65535）、icmp（PINGなど）の各アクションを許可（allow）し、それ以外は拒否（deny）する設定を追加します
> cf. [パケットフィルタを活用したサーバのセキュリティ対策 – 「さくらのクラウド入門」(9) - さくらのナレッジ](http://knowledge.sakura.ad.jp/sacloud/7133/)

---------------------

>  22、80、443、tcp・udp/1024～65535 をあけてあとは全拒否

**Comment by miya0001** [comment]
現在は以下のような感じになっています

![](https://www.evernote.com/l/ABW1TJRxP0xH05DcXQ3r6kmnoKlVt5OIGdQB/image.png)
