### ISSUE TITLE
サーバにsshできなくなった

### ISSUE THREAD

**Issue by uebo** [coderdojo-japan/dojopaas#49]
どうも初めまして。
昨日(2017/8/3 23時ごろ)、サーバにssh出来ていたんですが、本日（2017/8/4 9時ごろ）はssh出来なくなってしまいました。鍵などの情報は全く触っていません。

IP
133.242.231.67

障害情報には特に情報は載ってませんでした。
http://support.sakura.ad.jp/mainte/?service=cloud

何かわかるところあれば教えていただけますでしょうか 🙏

**Comment by yasulab** [comment]
こちら調べて見ますね 👀

**Comment by yasulab** [comment]
サーバー自体は動いているようですね🤔

<img width="1459" alt="screen shot 2017-08-04 at 10 30 37" src="https://user-images.githubusercontent.com/155807/28950570-09fa04fe-7900-11e7-87c7-bf8154a89b94.png">

**Comment by yasulab** [comment]
パッとコマンド履歴を見た感じだと、怪しそうなコマンドとしてはこれですかね? 🤔

`$ sudo ufw default DENY`

これで ssh port が閉じちゃって閉まったとか。

**Comment by yasulab** [comment]
`ufw status` で見ると ssh 用のポートが閉じてしまっていたので、`$ sudo ufw allow ssh` を実行しておきまた 🔧 💨 これでどうですかね? 😅

**Comment by uebo** [comment]
すみません、sshのことを考えずに自分でポートを閉じてしまいました。。
アクセスできることを確認しました！
ご対応感謝いたします 👍
