### ISSUE TITLE
リストから行が削除されたらそのサーバーを削除しちゃう?

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/dojopaas#5]
[CSV](https://github.com/coderdojo-japan/dojopaas/blob/master/servers.csv)を一行削除すればサーバーが削除できる。そう、`dojopaas`ならね。

**Comment by miya0001** [comment]
Travis CIの過去ログからRestartした時に、行が削除されたとご認識されてしまう可能性があって、この機能を実装するとそのときにインスタンスがまとめて削除されてしまうこともあり得るのですが、これを判別するいい方法がぱっと思いつかない。。。

**Comment by yasulab** [comment]
🤔💭 ( @cognitom さんは、CSV経由でサーバーを削除する処理について良いアイデアを持っていたりしないかな?)

**Comment by miya0001** [comment]
とりあえず slack のスラッシュコマンドで対応ということで、何か思いついたら再びオープンするかも。
