### ISSUE TITLE
SSHのポートを閉じてしまうケースが発生する

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/dojopaas#50]
#49 のようなSSHのポート番号を閉じてアクセスできなくなるケースが発生していますね。全く同じことが
 CoderDojo 調布でも発生していたので、今後も同じことが起こる可能性が高いと感じています🤔

@miya0001 さん、とりあえず次のコマンドを打てば解決するので、これって Slack から実行できたりしますかね? 🤔 

`$ sudo ufw allow ssh`

Slack からの実行イメージ: `/sacloud exec SERVER_ID sudo ufw allow ssh`

**Comment by yasulab** [comment]
🤔.oO(`exec` だとちょっと範囲がおおきすぎて危険な香りもするので、安全側に倒すなら `$ sudo ufw allow ssh` だけを実行できる特殊コマンドでも良いかもしれないですね)

**Comment by miya0001** [comment]
起動時に以下のシェルスクリプトを実行しておりまして、80, 443, 22以外は閉じております！
逆に言えば、開ける以外の操作はしなくてもいいよってアナウンスするという手もありかも。
https://github.com/coderdojo-japan/dojopaas/blob/master/startup-scripts/112900928939

Slackからやるのは難しいかもしれないですね。
Slackで解決するならそのインスタンスを捨てて、Travisをrestartすることで再度作り直しされます。

**Comment by miya0001** [comment]
あっ、捨てるというのは `/sacloud destroy <id>` という意味です。

**Comment by yasulab** [comment]
> 逆に言えば、開ける以外の操作はしなくてもいいよってアナウンスするという手もありかも。

こちらの方が簡単そうですね ;) 早速 README に追記してみました! 📝 https://github.com/coderdojo-japan/dojopaas/commit/31332db8199acbccd60fe3685c04f13b2f181f8a

> Slackで解決するならそのインスタンスを捨てて、Travisをrestartすることで再度作り直しされます。

@miya0001 なるほど! そうすると、もし同じような状況が今後発生した場合は、次のように対処すれば良いですかね?  🤔

1. Slack から `/sacloud destroy <id>` で当該サーバーを削除する ✂️ 
2. 適当に空コミット or Travis CI を Restart する 🔧 💨 
3. [instances.csv](https://github.com/coderdojo-japan/dojopaas/blob/gh-pages/instances.csv) に新しいサーバーが追加されたことを確認する 👀 ✅

**Comment by miya0001** [comment]
> こちらの方が簡単そうですね ;) 早速 README に追記してみました!

👍 

> 1. Slack から `/sacloud destroy <id>` で当該サーバーを削除する ✂️ 
> 2. 適当に空コミット or Travis CI を Restart する 🔧 💨 
> 3. [instances.csv](https://github.com/coderdojo-japan/dojopaas/blob/gh-pages/instances.csv) に新しいサーバーが追加されたことを確認する 👀 ✅ 

はい、この手順で問題ありません。
まれにサーバーの起動がAPIのタイムアウト等でコケることもあると思うのですが、その場合も同様の方法で再度サーバーを作り直すようになっています。

**Comment by yasulab** [comment]
ありがとうございます! 😆 とりあえず README への説明文の追記と、問題発生時の対策が共有できたので、この Issue は一旦 Close しますね ;)

ご協力ありがとうございました! 😸 ✨
