### ISSUE TITLE
さくらインターネットからの記事執筆の依頼

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/dojopaas#51]
@NorifumiOgawa @kamera25 @uebo @yumaS19 @coderdojofunabashi @togazo @4tera @gohomej @clown-morish @ogom @kwaka1208 @champierre @takatofu @zyasuda @digitarhythm @coderdojofujisawa 

さくらインターネットから次の記事執筆依頼が来たのですが、どなたか対応できる方はいらっしゃいますか? 🤔 対応できる方がいらっしゃれば、コメントをいただけると嬉しいです 🙇 

> 現在当社では、コミュニティイベントで配布しているチラシ
> 「さくらのオフライン通信」という紙のメディアを定期的に
> 制作しているのですが、こちらに、以下のような内容の
> 記事を書いていただくことは可能でしょうか？
> 
> 特に謝礼等お渡しできる前提のお話ではなく、大変恐縮では
> ございますが、一度ご検討いただけますと幸いです。
> 
> ## 内容イメージ
> 
> - CoderDojoの活動のご紹介
> - さくらのサービスをご活用いただいたケースのご紹介
> - 活動の様子の写真(1～2枚)
> 
> ### ご提出いただきたい内容
> 
> - タイトル（長さ：～50文字程度）：
> - 執筆者情報
>     - お名前(ハンドルネーム)：
>     - 所属：
>     - 肩書など：
>     - プロフィール(長さ～50文字程度)：
> - 本文テキスト（長さ：600文字～1,000文字程度）
> - 活動の様子の写真(1～2枚)
>     - ※記事に掲載させていただく為、肖像権、著作権等の承諾が得られているもの
> 
> ### 備考
> 
> - 掲載媒体: さくらのオフライン通信（紙媒体、A4、1枚を予定）
> - 配布予定枚数: 1,000枚程度
> - 配布予定期間: 2017/10/1～2017/12/31
> - 配布場所: 当社が関わるコミュニティイベント(CoderDojo関連か否かに関わらず)
> - 原稿締切: できれば8月中でお願いできますと幸いです。
> 
> 尚、いただきました原稿につきましては、紙面サイズの都合等により、
> 当社都合にて執筆者の承諾なく一部表現等を編集させていただく場合が
> ございます点、予めご了承いただけますと幸いです。

**Comment by yasulab** [comment]
@miya0001 こちらの件ですが、dojopaas をサーバー利用事例として書くと面白いのかなぁと考えていて、僕の方でこちらの記事を執筆してみようかなと考えていますが、その際、宮内さんに dojopaas の技術的な部分をレビューしてもらうことって可能ですかね? 🤔

dojopaas は利用事例としても面白いと思いますし、CoderDojo 全体の紹介にもなるので、今回は僕の方で記事を執筆してみようかなと思います ;)

**Comment by yasulab** [comment]
メール sent 📨 

> ご連絡遅れてしまってすみません >< CoderDojo Japan の安川です。
> こちらの件、色々と考えた結果、僕の方で対応しようかなと考えています!
> 
> ちょっとメタな利用事例で恐縮ですが、DojoPaaS という、CoderDojo Japan が全国の CoderDojo 向けに作った OSS の簡易 PaaS があるので、こちらを利用事例として紹介したいと考えています。
> 
> DojoPaaS ~ CoderDojo のためのサーバー利用申請手続き
> https://github.com/coderdojo-japan/dojopaas
> 
> 技術的にも面白い OSS プロジェクトで、実際に全国の CoderDojo 運営者にもご利用していただいている状態なので、他のコミュニティにとっても参考になりやすい事例かな思います。このような利用事例でも大丈夫でしょうか? 
> 
> サーバー利用申請の例まとめ
> https://github.com/coderdojo-japan/dojopaas/pulls?q=is%3Apr+is%3Aclosed
> 
> もしこのような事例でもよければ、僕の方で執筆しようかなと考えています! ご検討のほど、よろしくお願いいたします ;)
> 
> 安川

**Comment by miya0001** [comment]
はい、大丈夫です！

**Comment by yasulab** [comment]
ありがとうございます! では僕の方で草案を描いてみますね ;) 📝 💨

**Comment by yasulab** [comment]
先方からオッケーをもらえたので、僕の方で執筆する形で進めようと思いますね ;)

> すごく面白そうなネタで興味津々です。
> ぜひよろしくお願いいたします！

**Comment by miya0001** [comment]
ちなみにDojoConのインフラを構築したのですが、それにはこれを使用しています。
https://github.com/vccw-team/vccw-cloud

簡単にいうと Ansibleベースの構成管理ツールで、これを使用すると数回のコマンドでWordPress + SSL + HTTP/2 なバーチャルホスト環境を作れます。

**Comment by miya0001** [comment]
（ちょっと宣伝してもらえるとうれしいです！笑）

**Comment by yasulab** [comment]
まずは DojoPaaS を中心に書いてみて、もしどこか繋げそうな箇所があれば (文字数などを考慮しつつ) 検討してみます!

**Comment by yasulab** [comment]
@miya0001 原稿を書いてみました! 一度ご確認してもらえると嬉しいです 🙏  cc/ @tkc49 
(文字数的に1,000文字をギリギリ超えちゃった分量なので、vccwに関する情報は追加できなさそうです 💦 )

# 原稿

- タイトル: 
- 執筆者情報:
	- 名前: 安川 要平 (@yasulab)
	- 所属・肩書き: CoderDojo Japan代表理事 / YassLab代表
	- プロフィール: 早稲田大学大学院卒 (工学修士)、Railsチュートリアル・Railsガイド共同発起人、IPA未踏スーパークリエータ

## 本文テキスト

**本文: 1039文字**

CoderDojoはOSSコミュニティを中心に始まった、子どものためのプログラミング道場です。これまでのOSSコミュニティと同様に、CoderDojoが掲げる理念 (例: 非営利活動であること、性別・人種などに関係なく参加者を歓迎することなど) に同意していただければ、誰でも参画したり立ち上げたりすることができます。詳細: https://coderdojo.jp/

CoderDojoは2011年度にアイルランドで始まった活動です。その後イギリスやアメリカにも渡り、2012年度には日本でも活動が始まりました。当時は下北沢オープンソースCafeで小さく始まった活動ですが、徐々に全国に伝わっていき、2017年8月には全国90ヶ所以上、世界では1,250ヶ所以上にまで発展しました。現在は、全国様々な地域でコミュニティ活動が定期的に開催されています。

![coderdojo](https://user-images.githubusercontent.com/155807/29909847-aaa62bb8-8e62-11e7-9c25-23bf194071df.png)
写真1: CoderDojo 下北沢の様子

![coderdojo](https://user-images.githubusercontent.com/155807/29909866-b7dec844-8e62-11e7-9f38-bad163875483.png)
写真2: CoderDojo 西宮・梅田の様子

2017年7月にはSAKURA Internetさんが公式スポンサーに加わり、全国のCoderDojoを対象とした「さくらのクラウド」の提供が始まりました。

とはいえ全国に90ヶ所以上もあるので、各道場に１台ずつサーバーを渡すだけでも大変です (汗)。しかしそこはOSS発のコミュニティ、技術が好きな人達が全国から集まっているので、OSSコミュニティらしく技術で解決する手段を選びました。それが「DojoPaaS」です。URL: https://github.com/coderdojo-japan/dojopaas

「DojoPaaS」は、GitHubベースでサーバーを提供するOSSの簡易PaaSです。プルリクエスト形式でサーバー申請を出すことができ、管理者がCI結果および申請内容を確認し、Mergeボタンを押すことで申請が受理されます。マージされるとTravis CI経由でさくらのクラウドAPIが叩かれ、当該道場向けのサーバーが生成されるといった流れになっています。

このシステムはWordPressコミュニティの@miya0001さんと、Rubyコミュニティの私 (@yasulab) が一緒に開発したもので、MITライセンスで公開されています。CoderDojoでは様々なOSSコミュニティが横断的に関わっているので、こうやって一緒に何かを作ることができます。こういうの、僕はとても楽しいと思うんですよね。皆さんもぜひ、お近くのCoderDojoに遊びに行ってみてはいかがでしょうか? きっと面白い気づきが得られるのではないかなと思います ;)

**Comment by miya0001** [comment]
いいと思います！

**Comment by yasulab** [comment]
確認ありがとうございます! 😆 さくらインターネットの担当者からの返事を待って、受理されたらこの Issue は Close しますね 😸

**Comment by yasulab** [comment]
こちらの件すっかり閉じ忘れてましたが、無事受理されたので Issue 閉じますね ;)
