### ISSUE TITLE
管理者向けのハンドブック

### ISSUE THREAD

**Issue by miya0001** [coderdojo-japan/dojopaas#57]
管理者向けのドキュメントが必要

**Comment by miya0001** [comment]
たとば僕もコミッターの一人をやってるwp-cliでは、ワークフロー上のどんなささいなトラブルでも、handbookというドキュメントサイトに反映する習慣になっていて、結果的にほぼ毎日更新されています。
https://github.com/wp-cli/handbook/pulls?q=is%3Apr+is%3Aclosed

たとえば以下はコミッターが何かコミットするためのワークフローを書いたもの
https://github.com/wp-cli/handbook/blob/master/repository-management.md

**Comment by yasulab** [comment]
おぉ、wp-cli ではこんな感じにハンドブックを更新しているんですね! 参考になります ✨  📑 👀

**Comment by manzyun** [comment]
横から失礼します。札幌地域のメンターをやっております高橋です。

Ubuntuサーバーですので、とりあえず [Debian 管理者ハンドブック](https://debian-handbook.info/browse/ja-JP/stable/) と、[Ubuntuサーバーガイド（一部未翻訳あり）](https://help.ubuntu.com/lts/serverguide/index.html)　をお手元にというスタイルがいいのかなと思います。 :green_book:

「ハードルたけぇよ :scream:」  
など、遠慮なくおっしゃってください！

**Comment by yasulab** [comment]
一般的なサーバー管理に対する参考リンクとして便利そうですね ;)
それとは別に、DojoPaaS そのもののハンドブックも必要かなという認識です🤔

**Comment by yasulab** [comment]
Temporarily fixed by https://github.com/coderdojo-japan/dojopaas/pull/70 ✅ Thanks @manzyun!
