### ISSUE TITLE
さくらのクラウドのコンパネのパスワードを変更

### ISSUE THREAD

**Issue by miya0001** [coderdojo-japan/dojopaas#58]
Slack の #sakura チャンネルにいる人達にコンパネのパスワードが共有されている一方、現状ではさくらのコンパネに入る必要性は、DojoPaasのデバッグ以外ではほとんどないので、コンパネのパスワード変えません？

なにかあったときに原因の経路を調べるのがとても困難になってしまいます。

**Comment by yasulab** [comment]
変えます! 🔧💨 パスワードは @miya0001 さんと CoderDojo Japan 理事 (@yasulab @tkc49) の３人で共有すれば良いかなと考えていましたが、他にも追加した方が良さそうな人あればコメントください 🙏 

とりあえず変更だけ進めちゃいますね ;)

**Comment by miya0001** [comment]
とりあえず、僕もしばらくパスワードを知らない状態で頑張ってみます。笑

**Comment by miya0001** [comment]
情報共有コストを減らすっていうのは僕達の仕事の重要テーマだと思うのでこの機会に試したいです！

**Comment by yasulab** [comment]
了解です! 🙆 それでは僕と細谷さんで共有しておきますね ;) 必要になった段階でいつでも共有はできると思うので、その際は @yasulab までメンションください 🔔

**Comment by yasulab** [comment]
変更しました! こちらの Issue は閉じますね ;)
