### ISSUE TITLE
サーバーの削除・再生成をまとめて実行する方法をPRで対応したい

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/dojopaas#67]
現状では次のどちらかで対応する必要があります。

1. 管理者が Slack 上で削除し、Travis をリスタート
2. ~~運営者が削除するPRを出し、再度作成するPRを出す~~ => うまく動いてなさそう https://github.com/coderdojo-japan/dojopaas/pull/68#issuecomment-338042093

CoderDojo 運営者から「サーバーを一から作り直したい」という要望がよく来るので、「サーバーを初期状態に戻す」という要望をPRで受け付けられるメソッドがあると良さそうです 🤔💭 cc/ @miya0001 

cf. https://github.com/coderdojo-japan/dojopaas/issues/50

**Comment by miya0001** [comment]
そうですねー、でもちょっと難しいかもです。
プルリクストの時の差分を取れるといいんですけどね。要はどの行が削除されたかをTravis CI側で知る方法があればいけるのですが、現状はその方法がわかってないので、どのサーバーを削除すべきかを判別する方法がないんです。

**Comment by nalabjp** [comment]
経緯ややりたいことなど、ちゃんと理解できている自信はないので的外れでしたらゴメンナサイ。

> どの行が削除されたかをTravis CI側で知る方法があれば

だいぶ雑な作りなんですが、こういうことだったりしますでしょうか？
https://github.com/nalabjp/dojopaas/pull/1
https://travis-ci.org/nalabjp/dojopaas/builds/290085095#L472-L487

コミットハッシュはTravis CIのビルドごとの環境変数から取得しました。
https://docs.travis-ci.com/user/environment-variables/

**Comment by yasulab** [comment]
> 運営者が削除するPRを出し、再度作成するPRを出す

何度か Restart してみましたが、そもそも servers.csv を削除してもサーバーが削除されてなさそうです 🤔💦 
https://github.com/coderdojo-japan/dojopaas/pull/68#issuecomment-338042093

2. の方法がうまくいかなさそうなので、現状では 1. で対応するしかなさそう 😓

**Comment by miya0001** [comment]
現時点で自動削除はまったく対応してないので、slackのコマンドで `/sacloud destroy` をするかさくらのクラウドのコントロールパネルで削除するかしないと削除されないです。
（そもそも頻繁につくりなおすことを想定してないんですよね。汗）

でもこれ実際問題として /sacloud で削除するのめんどくさいですか？
現状であれば以下の手順です。

1. `/sacloud halt`で停止して`/sacloud destroy`でサーバーを削除
2. Travis CIをRestartすれば新しいサーバーができあがる。

この間に必要なやりとりはサーバーを削除してくださいという何らかの方法での連絡と終わりましたというやりとりだけです。

プルリクエストのやりとりでサーバーをつくりなおすには最低2回のプルリクエストのやりとりが必要になります。

あっ、要は開発コストの問題というかぶっちゃけそれほど全体の手間がかわらないのなら、頑張って開発するモチベーションが。。。笑
でも他の人もプルリクくれたりしていろいろ改善できるならなんでもやってみたいですね！

@nalabjp 

もしかしたらそうかもですね。コミットのハッシュが取れるならdiffをパースして削除されたサーバーのIDをとれるかもですね。

**Comment by yasulab** [comment]
> 現時点で自動削除はまったく対応してない

おぉ、勘違いしてました 💦 

> でもこれ実際問題として /sacloud で削除するのめんどくさいですか？

この作業に到るまでが負担がかかっていて辛いですね 😓 問い合わせが来る度に https://github.com/coderdojo-japan/dojopaas/issues/49 のような対応を僕がしているのですが、このままだとマズいなという危機感を持っています💦 

技術的に解決する前に、運用で解決するという手もありそうですね。例えば「初期化したい場合」「SSHで接続できなかった場合」みたいなFAQを README に書くだけでも違うのかも 🤔💭 (試してみる価値はありそう)

cf. https://github.com/coderdojo-japan/dojopaas/issues/57

**Comment by miya0001** [comment]
なるほど。オペレーションミスのサポートとか入り出すと確かに大変ですね。。。

**Comment by yasulab** [comment]
> 例えば「初期化したい場合」「SSHで接続できなかった場合」みたいなFAQを README に書くだけでも違うのかも 🤔💭 (試してみる価値はありそう)

まずはこちらで対応しました ;)

**Comment by yasulab** [comment]
あとすみません、READMEやドキュメントを直す程度のコミットに毎回PR出すのが面倒なので `Include administrators` の項目のチェックを外させてもらいました 🔓  💦 
https://github.com/coderdojo-japan/dojopaas/settings/branches/master

<img width="296" alt="screen shot 2017-10-26 at 12 46 22" src="https://user-images.githubusercontent.com/155807/32034143-b8a1471a-ba4b-11e7-8161-ed5514540aa6.png">
