### ISSUE TITLE
サーバー申請のPRはマージされたがinstances.csvに行が追加されない

### ISSUE THREAD

**Issue by kztakaoka** [coderdojo-japan/dojopaas#74]
福岡Dojoの高丘と申します。お世話になっております。
#73 で福岡Dojoサーバーの申請はマージしていただきましたが、instances.csvがコミットされていません。
coderdojo-fukuoka インスタンスはすでに起動している状態でしょうか？

**Comment by yasulab** [comment]
すみません、現在 dojopaas は壊れているようで、その原因を調査しています💦 @miya0001 さんに見てもらえると嬉しいのですが、 @miya0001 さんとちょっと連絡がついていないので、対応するのに結構時間がかかってしまいそうです >< 💦 

問題が解決するまでの間、少々お待ちいただけると幸いです 🙏

**Comment by yasulab** [comment]
@kztakaoka 今回は手動でサーバーを立ち上げて見ました。下記のサーバーを生成し、いただいた公開鍵を登録してみたので、SSHで接続を試してみてもらっても良いでしょうか? 🤔

`133.242.224.97`

**Comment by kztakaoka** [comment]
@yasulab さん、SSH接続できました！ありがとうございます！

**Comment by yasulab** [comment]
@kztakaoka よかったです! 今回は手動でサーバーを生成しただけで、表題の Issue が解決したわけではないので、こちらの Issue はまだこのままにしていただけると助かります 🙏 💦

**Comment by kztakaoka** [comment]
承知しました。

**Comment by miya0001** [comment]
あっ、気がついてなくてすいません。travisをrestartしてもダメだったんですか？

**Comment by yasulab** [comment]
はい、restartしてもダメでした 😭

**Comment by miya0001** [comment]
ざっと調べたんですがさくらのAPIの仕様がどこか変わってますね。。。

**Comment by yasulab** [comment]
なんと... 🙀

**Comment by yasulab** [comment]
#75 をマージしたので、うまく動いていることが確認できたらこちらの Issue は閉じますね ;) ただ今日はもう眠いので、テストは明日以降やりますね 😴 💤

**Comment by yasulab** [comment]
@kztakaoka DojoPaaS が無事に直って、[instances.csv](https://github.com/coderdojo-japan/dojopaas/blob/gh-pages/instances.csv#L22) に `coderdojo-fukuoka` が追加されました! (Thx miya0001 さん! 😸)
https://github.com/coderdojo-japan/dojopaas/pull/75

よければ先日お渡ししたサーバーではなく、[instances.csv](https://github.com/coderdojo-japan/dojopaas/blob/gh-pages/instances.csv#L22) にある方のサーバーを使っていただけると嬉しいのですが、ご対応していただくことは可能でしょうか? 🤔

**Comment by kztakaoka** [comment]
@yasulab ありがとうございます！しかし、
instances.csv の153.120.171.70に接続してみたところ、
> ssh: connect to host 153.120.171.70 port 22: Operation timed out

となります。。
pingは、
　先日のサーバー（133.242.224.97）：OK
　153.120.171.70: Request timeout
となりました。

**Comment by yasulab** [comment]
おっと、ちょっとサーバーの状態を確認して見ますね 💻  👀

**Comment by yasulab** [comment]
@kztakaoka 再起動させてみました! もう一度 SSH で接続して見てもらっても良いですか? 🤔

**Comment by kztakaoka** [comment]
接続できました！ありがとうございます！

**Comment by kztakaoka** [comment]
こちらを使用しますので、先日のサーバーは不要で問題ありません。
ありがとうございます！

**Comment by yasulab** [comment]
ご確認ありがとうございます😸 古い方のサーバーを削除したので、それではこちらの Issue は閉じちゃいますね ;)

また何かあればお気軽にご連絡ください! 😆
