### ISSUE TITLE
サーバーの初期化依頼

### ISSUE THREAD

**Issue by yu-san-19** [coderdojo-japan/dojopaas#77]
CoderDojo 岡山 岡南の曽我です。当該サーバーの初期化をお願いします。

**Comment by yasulab** [comment]
@yu-san-19 当該サーバーを初期化しました! 確認お願いします 😸 
https://github.com/coderdojo-japan/dojopaas/commit/b74dba6a2e378dbfa36ea881729591fecca05fb5#diff-3dfe38357946121c2f0b04a2f80cec54R23

**Comment by yu-san-19** [comment]
@yasulab 遅くなりました、すみません。
初期化、ありがとうございます。無事繋がりました！

**Comment by yasulab** [comment]
無事に繋がってようで良かったです! 😸
