### ISSUE TITLE
複数の公開鍵を登録

### ISSUE THREAD

**Issue by miya0001** [coderdojo-japan/dojopaas#8]
各インスタンスごとに複数の管理者の公開鍵を設定できるようにした方がいいかもしれない

**Comment by miya0001** [comment]
CSVだと複数の何かってむずかしいですね。。。

**Comment by miya0001** [comment]
サーバー起動後に管理者が自力で公開鍵を登録すればいいかなということで。。。

**Comment by yasulab** [comment]
今の所そういった声は聞いていないので、僕も大丈夫だと思います! 👍
