### ISSUE TITLE
instances.csv に結果が反映されない

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/dojopaas#82]
servers.csv を更新することでサーバーを生成することはできるのですが、生成したサーバー情報を instances.csv に反映する部分がうまく動かなくなっているようです >< 💦 何度か Restart しても再現してしまうので、現状では、`/sacloud list` を実行して手動でIPアドレスを伝える形で対応しています 📑 👀  (例: https://github.com/coderdojo-japan/dojopaas/pull/80 )

@miya0001 よければお手すきの際に調べてもらえると嬉しいです 🙏 

## エラー内容

<summary>TypeError: Cannot read property 'status' of undefined</summary>
<details>
<pre>
285.07s$ bash ./bin/deploy.sh
> dojopaas@1.0.0 deploy /home/travis/build/coderdojo-japan/dojopaas
> node dojopaas.js "--production"
Update startup scripts.
Archive ID:112901411351
Get a list of existing servers.
Create a server for coderdojo-hirakata.
Create a network interface.
Connect network interface.
Apply packet filter.
Create a disk.
Connect to the disk.
Setup ssh key.
409 Conflict
Copying image for coderdojo-hirakata...
409 Conflict
Copying image for coderdojo-hirakata...
409 Conflict
Copying image for coderdojo-hirakata...
409 Conflict
Copying image for coderdojo-hirakata...
409 Conflict
Copying image for coderdojo-hirakata...
409 Conflict
Copying image for coderdojo-hirakata...
409 Conflict
Copying image for coderdojo-hirakata...
Start server: 113000011707 for coderdojo-hirakata.
The `instances.csv` was saved!
/home/travis/build/coderdojo-japan/dojopaas/lib/Server.js:157
            console.log(result.response.status);
                                       ^
TypeError: Cannot read property 'status' of undefined
    at /home/travis/build/coderdojo-japan/dojopaas/lib/Server.js:157:40
    at _Request._onReadyStateChangeOnXHR (/home/travis/build/coderdojo-japan/dojopaas/node_modules/sacloud/lib/sacloud/client.request.js:126:4)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/travis/build/coderdojo-japan/dojopaas/node_modules/xhr2/lib/xhr2.js:64:9)
    at XMLHttpRequest._setReadyState (/home/travis/build/coderdojo-japan/dojopaas/node_modules/xhr2/lib/xhr2.js:360:12)
    at XMLHttpRequest._onHttpResponseEnd (/home/travis/build/coderdojo-japan/dojopaas/node_modules/xhr2/lib/xhr2.js:478:12)
    at IncomingMessage.<anonymous> (/home/travis/build/coderdojo-japan/dojopaas/node_modules/xhr2/lib/xhr2.js:442:22)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
npm ERR! Linux 4.9.6-040906-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v7.10.1/bin/node" "/home/travis/.nvm/versions/node/v7.10.1/bin/npm" "run" "deploy" "--" "--production"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dojopaas@1.0.0 deploy: `node dojopaas.js "--production"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dojopaas@1.0.0 deploy script 'node dojopaas.js "--production"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dojopaas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node dojopaas.js "--production"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dojopaas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls dojopaas
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/.npm/_logs/2018-01-04T05_23_24_768Z-debug.log
Done. Your build exited with 0.

</pre></details>
詳細: https://travis-ci.org/coderdojo-japan/dojopaas/builds/324902857

**Comment by yasulab** [comment]
とりあえずは `/sacloud list` を使って手動で伝えています 📨 
当該 Dojo とそのサーバー情報をこちらでまとめておきます 🔖 

## coderdojo-mishima-numazu
*ID*: 112901651187
*IP Address*: 153.127.199.120
*Status*: up

## coderdojo-umeda-nishinomiya
*ID*: 113000010161
*IP Address*: 153.125.129.106
*Status*: up

## coderdojo-hirakata
*ID*: 113000011707
*IP Address*: 133.242.238.190
*Status*: up

**Comment by miya0001** [comment]
おお、またなにかAPIが変わったのですね。。。汗

**Comment by miya0001** [comment]
手抜きな修正ですが治った気がします。 😊 
https://github.com/coderdojo-japan/dojopaas/commit/5904765951f536ae73bb3be61a774cc15fbb1ba0

**Comment by yasulab** [comment]
対応ありがとうございます! 😸 ✨ 
無事に push されていることを確認したので、こちらの Issue は閉じますね ;)
https://github.com/coderdojo-japan/dojopaas/commit/8174dd6a599582a36dffbb27a803d60f67fcd72a#diff-3dfe38357946121c2f0b04a2f80cec54R24
