### ISSUE TITLE
サーバーの初期化依頼

### ISSUE THREAD

**Issue by CoderDojoMishimaNumazu** [coderdojo-japan/dojopaas#83]
CoderDojo【三島沼津】の【長屋順子】です。当該サーバーの初期化をお願いします。
（すみません、いじっていたらsudoが使えなくなりました。お手数をおかけします。）

**Comment by yasulab** [comment]
再生成しました! 
https://github.com/coderdojo-japan/dojopaas/commit/63274b713290b6659508baf7ec2aee27c40fd5ba#diff-3dfe38357946121c2f0b04a2f80cec54R26
