### ISSUE TITLE
サーバーの初期化依頼

### ISSUE THREAD

**Issue by tsujimasahiro** [coderdojo-japan/dojopaas#86]
CoderDojo Nadaの辻　雅啓です。当該サーバーの初期化をお願いします。

**Comment by yasulab** [comment]
こちら、新しくサーバーを生成し直しました! 
https://github.com/coderdojo-japan/dojopaas/commit/9c9f6cd29eaba4aeb35c856ac863549ca716c0f4#diff-3dfe38357946121c2f0b04a2f80cec54R27

**Comment by tsujimasahiro** [comment]
安川様
接続確認、できました。
お手数かけました。
ありがとうございます。
CoderDojo NadaのWebサイトの準備を始めます。
辻 雅啓

2018-01-18 0:12 GMT+09:00 Yohei Yasukawa <notifications@github.com>:
