### ISSUE TITLE
サーバーの初期化依頼

### ISSUE THREAD

**Issue by manzyun** [coderdojo-japan/dojopaas#88]
CoderDojoSapporoEast（札幌東）の高橋秀羅（@manzyun）です。下記理由につき、当該サーバーの初期化をお願いします。

----

1. サーバー管理を弊DojoのChampion.安田から委任されました。
2. 2017年12月10日にChampionから伝えられたipアドレスと、譲渡していただいた秘密鍵での接続が、以下のような事象が発生しできませんでした。
    * sshでの接続を試みたところ、30秒後 `ssh: connect to host 153.120.166.97 port 22: Connection timed out` と表示される。
    * 他SSH接続（個人で使用しているBitbucketのリポジトリにSSHでの `git pull` 操作）で、手元の環境でのSSH接続のブロックをしていないことを確認。
    * `traceroute` コマンドでさくらインターネット様のサーバー（ `sac-is1b-rt1-rt101b.bb.sakura.ad.jp (103.10.113.50)` ）までの疎通は確認。

----

お手数おかけしますが、よろしくお願いいたします。

**Comment by manzyun** [comment]
@yasulab お願いします！🙇 　確認は18時以降になってしまうかもしれませんので、急がなくても大丈夫です👍

**Comment by yasulab** [comment]
先ほどコントロールパネルから調べてみたら、そもそもシャットダウン状態になってました 😅 先ほど起動してみたので、後ほどご確認してもらえれば ;)

**Comment by manzyun** [comment]
@yasulab ありがとうございます！　本業が終わったら確認してみます👍

**Comment by manzyun** [comment]
@yasulab SSHで接続できました！　ログインに関しては譲渡いただいた鍵ファイルにパスワードがついていたため、改めてPRを送って公開鍵を変更してもらう方針で行こうと思います。

**Comment by yasulab** [comment]
@manzyun PRの件、承知しました! ただ、PRをマージしただけではサーバー内のある authorized_keys は変更されません。SSHでログインした上で直接公開鍵を変更または追加する必要があるので、ご注意ください 🙏

**Comment by yasulab** [comment]
標題の Issue は解決されたので、こちらは close しますね ;)

**Comment by manzyun** [comment]
度々すみません。

SSHでの接続を試みたのですが、今回はサーバー側から

```
ubuntu@153.120.166.97's password: 
````

と問い合わせされ、 :roll_eyes: となったので、改めて鍵を再作成して、公開鍵の更新をさせていただきます。

:thought_balloon: *もしかしたら過去の自分が何かやらかしたのかなあ……そうなると改めて初期化ですかね。*

# P.S.

また、半年前ほどに思い描いていたCoderDojoマイクロブログサーバーを実験的に立ち上げてみたいので、descriptionにその旨も追加いたします。

**Comment by yasulab** [comment]
なるほど。ではサーバー初期化で対応してみますね

**Comment by yasulab** [comment]
間違って close してしまった 💦 初期化したら close します!

**Comment by yasulab** [comment]
サーバーを初期化しました!
https://github.com/coderdojo-japan/dojopaas/commit/9ff1f04fa49fd4f1ac863ab0f417f7fad36385e4
